In [423]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [424]:
df = pd.read_csv("cust_satisfaction.csv")
df.head()

Gender      Customer Type   Type of Travel     Class  \
0    Male     Loyal Customer  Personal Travel  Eco Plus   
1    Male  disloyal Customer  Business travel  Business   
2  Female     Loyal Customer  Business travel  Business   
3  Female     Loyal Customer  Business travel  Business   
4    Male     Loyal Customer  Business travel  Business   

              satisfaction  Age  Flight Distance  Inflight entertainment  \
0  neutral or dissatisfied   13              460                       5   
1  neutral or dissatisfied   25              235                       1   
2                satisfied   26             1142                       5   
3  neutral or dissatisfied   25              562                       2   
4                satisfied   61              214                       3   

   Baggage handling  Cleanliness  Departure Delay in Minutes  \
0                 4            5                          25   
1                 3            1                           1   
2                 4            5                           0   
3                 3            2                          11   
4                 4            3                           0   

   Arrival Delay in Minutes  
0                      18.0  
1                       6.0  
2                       0.0  
3                       9.0  
4                       0.0

In [425]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Gender                      103904 non-null  object 
 1   Customer Type               103904 non-null  object 
 2   Type of Travel              103904 non-null  object 
 3   Class                       103904 non-null  object 
 4   satisfaction                103904 non-null  object 
 5   Age                         103904 non-null  int64  
 6   Flight Distance             103904 non-null  int64  
 7   Inflight entertainment      103904 non-null  int64  
 8   Baggage handling            103904 non-null  int64  
 9   Cleanliness                 103904 non-null  int64  
 10  Departure Delay in Minutes  103904 non-null  int64  
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(6), object(5)
memory usage: 9.5+ MB


In [426]:
df.isnull().sum()

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
satisfaction                    0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      310
dtype: int64

In [427]:
df.dropna(inplace = True)

In [428]:
df.duplicated().sum()

172

In [429]:
df.drop_duplicates()

Gender      Customer Type   Type of Travel     Class  \
0         Male     Loyal Customer  Personal Travel  Eco Plus   
1         Male  disloyal Customer  Business travel  Business   
2       Female     Loyal Customer  Business travel  Business   
3       Female     Loyal Customer  Business travel  Business   
4         Male     Loyal Customer  Business travel  Business   
...        ...                ...              ...       ...   
103899  Female  disloyal Customer  Business travel       Eco   
103900    Male     Loyal Customer  Business travel  Business   
103901    Male  disloyal Customer  Business travel  Business   
103902  Female  disloyal Customer  Business travel       Eco   
103903    Male     Loyal Customer  Business travel  Business   

                   satisfaction  Age  Flight Distance  Inflight entertainment  \
0       neutral or dissatisfied   13              460                       5   
1       neutral or dissatisfied   25              235                       1   
2                     satisfied   26             1142                       5   
3       neutral or dissatisfied   25              562                       2   
4                     satisfied   61              214                       3   
...                         ...  ...              ...                     ...   
103899  neutral or dissatisfied   23              192                       2   
103900                satisfied   49             2347                       5   
103901  neutral or dissatisfied   30             1995                       4   
103902  neutral or dissatisfied   22             1000                       1   
103903  neutral or dissatisfied   27             1723                       1   

        Baggage handling  Cleanliness  Departure Delay in Minutes  \
0                      4            5                          25   
1                      3            1                           1   
2                      4            5                           0   
3                      3            2                          11   
4                      4            3                           0   
...                  ...          ...                         ...   
103899                 4            2                           3   
103900                 5            4                           0   
103901                 4            4                           7   
103902                 1            1                           0   
103903                 4            1                           0   

        Arrival Delay in Minutes  
0                           18.0  
1                            6.0  
2                            0.0  
3                            9.0  
4                            0.0  
...                          ...  
103899                       0.0  
103900                       0.0  
103901                      14.0  
103902                       0.0  
103903                       0.0  

[103422 rows x 12 columns]

In [430]:
df["Customer Type"].value_counts()

Customer Type
Loyal Customer       84662
disloyal Customer    18932
Name: count, dtype: int64

In [431]:
loyal_customer = df[df["Customer Type"] == "Loyal Customer"]
disloyal_customer = df[df["Customer Type"] == "disloyal Customer"]

In [432]:
loyal_customer = loyal_customer.sample(20000)
loyal_customer.shape

(20000, 12)

In [433]:
balance_df = pd.concat([loyal_customer, disloyal_customer], axis = 0)
balance_df.shape

(38932, 12)

In [434]:
cat_col = balance_df.select_dtypes(include = ["object"])
cat_col.head()

Gender   Customer Type   Type of Travel     Class  \
11932    Male  Loyal Customer  Business travel       Eco   
18497    Male  Loyal Customer  Business travel  Business   
2808     Male  Loyal Customer  Business travel  Business   
22108  Female  Loyal Customer  Business travel  Business   
8517   Female  Loyal Customer  Business travel  Business   

                  satisfaction  
11932  neutral or dissatisfied  
18497  neutral or dissatisfied  
2808                 satisfied  
22108                satisfied  
8517                 satisfied

In [435]:
num_col = df.select_dtypes(exclude = ["object"])
num_col.head()

Age  Flight Distance  Inflight entertainment  Baggage handling  \
0   13              460                       5                 4   
1   25              235                       1                 3   
2   26             1142                       5                 4   
3   25              562                       2                 3   
4   61              214                       3                 4   

   Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  
0            5                          25                      18.0  
1            1                           1                       6.0  
2            5                           0                       0.0  
3            2                          11                       9.0  
4            3                           0                       0.0

In [436]:
# cat_col["Gender"].value_counts()

In [437]:
# pd.get_dummies(cat_col["Gender"]).astype(int).head()
pd.get_dummies(cat_col, drop_first = True).astype(int).head()


Gender_Male  Customer Type_disloyal Customer  \
11932            1                                0   
18497            1                                0   
2808             1                                0   
22108            0                                0   
8517             0                                0   

       Type of Travel_Personal Travel  Class_Eco  Class_Eco Plus  \
11932                               0          1               0   
18497                               0          0               0   
2808                                0          0               0   
22108                               0          0               0   
8517                                0          0               0   

       satisfaction_satisfied  
11932                       0  
18497                       0  
2808                        1  
22108                       1  
8517                        1

In [438]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

one = OneHotEncoder(drop = "if_binary")
cat_col_encoded = one.fit_transform(cat_col).toarray()
cat_col_encoded

array([[1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.]])

In [439]:
column_name = list(one.get_feature_names_out())
column_name

['Gender_Male',
 'Customer Type_disloyal Customer',
 'Type of Travel_Personal Travel',
 'Class_Business',
 'Class_Eco',
 'Class_Eco Plus',
 'satisfaction_satisfied']

In [440]:
one_hot = pd.DataFrame(cat_col_encoded, columns = column_name)
one_hot.head()

Gender_Male  Customer Type_disloyal Customer  \
0          1.0                              0.0   
1          1.0                              0.0   
2          1.0                              0.0   
3          0.0                              0.0   
4          0.0                              0.0   

   Type of Travel_Personal Travel  Class_Business  Class_Eco  Class_Eco Plus  \
0                             0.0             0.0        1.0             0.0   
1                             0.0             1.0        0.0             0.0   
2                             0.0             1.0        0.0             0.0   
3                             0.0             1.0        0.0             0.0   
4                             0.0             1.0        0.0             0.0   

   satisfaction_satisfied  
0                     0.0  
1                     0.0  
2                     1.0  
3                     1.0  
4                     1.0

In [441]:
one_hot = one_hot.reset_index(drop = True)
num_col = num_col.reset_index(drop = True)
final_df = pd.concat([one_hot, num_col], axis = 1)
final_df.head()

Gender_Male  Customer Type_disloyal Customer  \
0          1.0                              0.0   
1          1.0                              0.0   
2          1.0                              0.0   
3          0.0                              0.0   
4          0.0                              0.0   

   Type of Travel_Personal Travel  Class_Business  Class_Eco  Class_Eco Plus  \
0                             0.0             0.0        1.0             0.0   
1                             0.0             1.0        0.0             0.0   
2                             0.0             1.0        0.0             0.0   
3                             0.0             1.0        0.0             0.0   
4                             0.0             1.0        0.0             0.0   

   satisfaction_satisfied  Age  Flight Distance  Inflight entertainment  \
0                     0.0   13              460                       5   
1                     0.0   25              235                       1   
2                     1.0   26             1142                       5   
3                     1.0   25              562                       2   
4                     1.0   61              214                       3   

   Baggage handling  Cleanliness  Departure Delay in Minutes  \
0                 4            5                          25   
1                 3            1                           1   
2                 4            5                           0   
3                 3            2                          11   
4                 4            3                           0   

   Arrival Delay in Minutes  
0                      18.0  
1                       6.0  
2                       0.0  
3                       9.0  
4                       0.0

In [442]:
# dividing the data into dependent and independent variables

x = final_df.drop("satisfaction_satisfied", axis = 1)
y = final_df["satisfaction_satisfied"]

In [443]:
# dividing the data into training and testing data

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

## needs attention!!! ##

In [444]:
x_train = x_train.dropna()
y_train = y_train.loc[x_train.index]

x_test = x_test.dropna()
y_test = y_test.loc[x_test.index]

In [445]:
from sklearn.linear_model import LogisticRegression

lgr = LogisticRegression()
lgr.fit(x_train, y_train)

c:\Users\Madhur\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [446]:
lgr.score(x_train, y_train)

0.7503379465722562

In [447]:
lgr.score(x_test, y_test)

0.7528618672093614

In [448]:
y_pred = lgr.predict(x_test)
y_pred

array([0., 0., 0., ..., 1., 0., 1.])

In [449]:
# x_train = x_train.dropna()
# y_train = y_train.loc[x_train.index]

# x_test = x_test.dropna()
# y_test = y_test.loc[x_test.index]

In [450]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))

[[4132  920]
 [1023 1787]]


In [451]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.80      0.82      0.81      5052
         1.0       0.66      0.64      0.65      2810

    accuracy                           0.75      7862
   macro avg       0.73      0.73      0.73      7862
weighted avg       0.75      0.75      0.75      7862

